### ISSUE TITLE
Smileys cant be encoded [Solved]

### ISSUE THREAD

**Issue by Sh4d0wnight** [GsDeluxe/Simple-Discord-Music-Bot#1]
Hey 
I got an Error where if i searched for a Video which had a Smiley in it, it wouldn't play the Song.

How to solve it?

Just add [ encoding="utf-8" ] to the [ with open("xyz") ] Commands

For Example:

 with open("now.txt", "w" , encoding="utf-8") --> line 134 in music_cog_v2

utf-8 is the Standard and should work for nearly everyone

**Comment by GsDeluxe** [comment]
Sorry for the late reply, but thank you for pointing this out. I have now updated the code. Thanks again

**Comment by Sh4d0wnight** [comment]
no Problem ^^
